### ISSUE TITLE
Refatorar a modelagem Ágil

### ISSUE THREAD

**Issue by juniopereirab** [Requisitos-de-Software/2019.2-Yellow#105]
**Descrição da issue**
Padronizar todas as histórias de usuário. 

**Tarefas**

- [ ] Fazer a padronização das histórias de usuário.
- [ ] Revisar a falta ou excesso de US e outros tópicos.
- [ ] Documentar corretamente com a versão certa do documento. 
- [ ] Adicionar na Wiki, mantendo a versão antiga para comparação.

**Critérios de aceitação**

- [ ] Modelagem Ágil atualizada.
- [ ] Documento contem todas as informações sobre, quem fez, como fez, quando fez, e a versão do documento.
- [ ] Wiki foi atualizada mantendo as versões anteriores.

**Comment by juniopereirab** [comment]
Criar o sprint backlog !!!

**Comment by heylisten64** [comment]
foi p validação
