### ISSUE TITLE
Verificação de artefatos!!!

### ISSUE THREAD

**Issue by juniopereirab** [Requisitos-de-Software/2019.2-Yellow#111]
**Descrição da issue**
Essa issue servirá como guia para ser feito a verificação dos artefatos do projeto como um todo.

**Artefatos**

- [x] Inspeção Gestão de Qualidade Total - **Letícia**
- [x] Inspeção Prototipação - **Letícia**
- [x] Inspeção QFD - **Letícia**
- [x] Inspeção Análise de Discurso - **Julio**
- [x] Inspeção MoSCoW - **Dâmaso**
- [x] Inspeção First things First - **Julio**
- [x] Inspeção 5W2H - **Julio**
- [x] Inspeção Análise de Protocolo - **Lucas**
- [x] Inspeção Ágil - **Lucas**
- [x] Inspeção Storyboard - **Lucas**
- [x] Inspeção Brainstorming - **Lucas**
- [x] Inspeção RichPicture - **Pedro**
- [x] Inspeção Questionários - **Pedro**
- [x] Inspeção Storytelling - **Pedro**
- [x] Inspeção Entrevistas - **Pedro**
- [x] Inspeção Personas - **Dâmaso**
- [x] Inspeção Cenários - **Dâmaso**
- [x] Inspeção Léxicos - **Letícia**
- [x] Inspeção Especificação Suplementar - **Julio**
- [x] Inspeção NFR  - **Gabi**
- [x] Inspeção Casos de Uso - **Gabi**
- [x] Inspeção Introspecção - **Gabi**
- [x] Inspeção Observação - **Gabi**

|**Gabriela**  | **Dâmaso** | **Lucas**  | **Júlio** | **Letícia**  | **Pedro** |
|--|--|--|--|--|--|
| Inspeção NFR  |  Inspeção Personas | Análise de Protocolo |Inspeção 5W2H|Inspeção Gestão de Qualidade Total|Inspeção Entrevistas|
| Inspeção Casos de Uso  | Inspeção Cenários  | Storyboard  |Inspeção Análise First Things First|Inspeção Prototipação|Inspeção Questionários|
| Inspeção Introspecção  | Inspeção MoSCoW | Ágil |Inspeção Análise de Discurso|Inspeção Léxicos|Inspeção Storytelling|
| Inspeção Observação  | | Brainstorming  | Inspeção Especificação Suplementar |Inspeção QFD|Inspeção RichPicture|

**Critério de Aceitação:**
- [ ] Foi utilizado alguma técnica de verificação (checklist, etc)
- [ ] Os critérios de avaliação estão bem descritos
- [ ] O artefato inspecionado, foi criado por outra pessoa.
- [ ] Está atualizado **NESTA ISSUE** o você está fazendo
- [ ] Está atualizado no Pages

**Comment by juniopereirab** [comment]
Não deve ser feito inspeção em cima de artefatos que você mesmo tenha feito.
Tentando manter a rotação de informações de forma que todos possam ter acesso e aprender sobre algo que não tenha feito durante o semestre.

**Comment by juniopereirab** [comment]
https://requisitos-habitica.netlify.com/

https://welisonr.github.io/2019.1-Requisitos-Brainly

https://github.com/Andre-Eduardo/2019.1-Requisitos-Moovit

**Comment by pedroeagle** [comment]
PRIORIDADE TOTAL PRA ESSAS INSPEÇÕES:

Ágil - Lucas @lucasgomesgs0 
Casos de Uso - Gabi @heylisten64 
Cenários - Dâmaso @juniopereirab 
Especificação Suplementar - Júlio @jclitwin 
Léxicos - Letícia @leticiaarj 
NFR - Gabi @heylisten64 
Rich Pictures - Pedro Igor @pedroeagle 

a gente tava olhando os outros grupos assim como habitica e não fizeram inspeção de todos os artefatos. escolhemos alguns que foram abordados pela maioria dos outros grupos e colocamos como prioridade. talvez hajam diferenças com o que está no github mas é pra que seja feito pra amanhã.

**Comment by pedroeagle** [comment]
cada autor de cada artefato que foi feita verificação na sprint passada deve fazer as alterações sugeridas na verificação. caso haja alguma dúvida tirem com o autor da verificação.

**Comment by pedroeagle** [comment]
como foi decidido em sala, faremos verificação apenas dos artefatos mais importantes já que estamos com pouco tempo. cada um ficará responsável pela refatoração a partir das verificações realizadas assim como outras refatorações decididas na reunião.
