### ISSUE TITLE
Revisar RichPicture

### ISSUE THREAD

**Issue by heylisten64** [Requisitos-de-Software/2019.2-Yellow#18]
Revisar RichPicture de acordo com a sugestão do professor.

**Tarefas**

- [x] Revisar o RichPicture criado para a atividade da disciplina.

**Critérios de aceitação**

- [x] RichPicture revisado, atendendo aos criterios levantados pelo professor, abordando todos os componentes vistos em sala de aula (actors, operations, data stores, arrows, system boundary).

**Comment by lucasgomesgs0** [comment]
![RichPicture2 0](https://user-images.githubusercontent.com/29768011/64582925-8f3fee00-d365-11e9-8a25-be8ab2260cff.png)
