### ISSUE TITLE
Elaborar documento da apresentação

### ISSUE THREAD

**Issue by heylisten64** [Requisitos-de-Software/2019.2-Yellow#21]
Criar e imprimir o documento a ser entregue no segundo ponto de controle. 

**Tarefas**

- [x] Criar o documento da apresentação do PC2.
- [x] Imprimir documento. 

**Critérios de aceitação**

- [x] Documento criado.
- [x] Documento impresso.

**Comment by juniopereirab** [comment]
O documento está sendo descrito em: https://docs.google.com/document/d/1aQCPAS0Gt_fZg0F7Gi8RaCTqJr238b_blrB4msTKnTM/edit
