### ISSUE TITLE
Elaborar 5w2h

### ISSUE THREAD

**Issue by heylisten64** [Requisitos-de-Software/2019.2-Yellow#27]

**Comment by pedroeagle** [comment]
Criei o 5W2H e adicionei a GH Pages.

# 5W2H

## What
Uma aplicação para aluguel de bicicletas e patinetes em toda a cidade.

## Why
Porque transportar uma bicicleta para um parque ou área de lazer nem sempre é uma tarefa simples. Porque existem trajetos que não são tão distantes para que necessitem de um carro ou um ônibus, e nem tão próximos para que seja feito caminhando.

## Where
Em qualquer lugar da cidade, no momento em Brasília e Águas Claras-DF. Tudo disponível na aplicação para smartphone.

## When
A empresa começou o desenvolvimento da aplicação em Junho de 2017.

## Who
Eduardo Musa e por Ariel Lambrecht e Renato Freitas, ambos co-fundadores da 99 pop (aplicação de transporte privado) que foi vendida para a chinesa Didi Chuxing em janeiro de 2018.

## How
Aplicativo mobile para Android e IOS.

## How Much
Investimento de 50 milhões de reais iniciais.

<br><br>
## Referências
Site de notícias Brasil 247, disponível em: https://www.brasil247.com/geral/fundadores-da-99-lancam-servico-de-bicicletas-yellow-em-sp Acesso em 09/09/2019
