### ISSUE TITLE
Elaborar storyboard

### ISSUE THREAD

**Issue by juniopereirab** [Requisitos-de-Software/2019.2-Yellow#32]
Fazer o storyboard do <i>Yellow</i>

**Tarefas**

- [x] Fazer o storyboard

**Critérios de aceitação**

- [x] Storyboard feito

**Comment by heylisten64** [comment]
![storyboard](https://user-images.githubusercontent.com/43069991/65823427-7c199300-e22c-11e9-8934-2cf8f5af8c26.jpg)

**Comment by heylisten64** [comment]
![storyboard](https://user-images.githubusercontent.com/43069991/65823429-89368200-e22c-11e9-8ce5-cf530dbb557e.jpg)

**Comment by heylisten64** [comment]
seria válido propor uma revisão pra fazer utilizando recursos como o Illustrator!
