### ISSUE TITLE
Revisar MoSCoW

### ISSUE THREAD

**Issue by heylisten64** [Requisitos-de-Software/2019.2-Yellow#37]
Revisar MoSCoW de acordo com a reaplicação do brainstorming.

**Tarefas**

- [x] Atualizar a técnica de priorização conforme o que foi levantado no novo brainstorming. 
- [x] Documentar a técnica em plataforma gráfica.
- [x] Documentar separadamente o que foi levantado a partir da técnica.
- [x] Documentar data, horário e pessoas envolvidas.

**Critérios de aceitação**

- [x] MoSCoW de acordo com as atualizações levantadas pela equipe.
- [x] MoSCow formulado na plataforma [draw.io](https://www.draw.io/), ou outra de preferência do autor de forma a permanecer nítido.
- [x] Informações levantadas a partir da técnica documentados separadamente.
- [x] Data, horário e pessoas envolvidas devidamente documentados.

**Comment by pedroeagle** [comment]
Foi sugerido pela @heylisten64 que o moscow fosse feito apenas em tabela sem a necessidade de uma imagem.
