### ISSUE TITLE
Realizar técnica de Implantação de Função de Qualidade

### ISSUE THREAD

**Issue by heylisten64** [Requisitos-de-Software/2019.2-Yellow#46]

**Comment by juniopereirab** [comment]
![0001](https://user-images.githubusercontent.com/17153869/65794156-ebfd2000-e13d-11e9-8b16-7cb4e0923d68.jpg)

Acima está representado a imagem da Casa da Qualidade (QFD). Técnica para priorização de requisitos.

**Comment by juniopereirab** [comment]
Solucionado no PR #56
