### ISSUE TITLE
Revisão de artefatos de Modelagem de Requisitos

### ISSUE THREAD

**Issue by juniopereirab** [Requisitos-de-Software/2019.2-Yellow#93]
**Descrição da issue**
Revisar todos os artefatos de Modelagem de Requisitos

**Tarefas**

- [x] Ágil
- [x] Casos de Uso
- [x] Cenários
- [x] Especificação Suplementar
- [x] Léxicos
- [x] NFR Framework

**Critérios de aceitação**

- [x] Foi feita a revisão e melhoria da Modelagem Ágil
- [x] Foi feita a revisão e melhoria dos Casos de Uso
- [x] Foi feita a revisão e melhoria dos Cénarios
- [x] Foi feita a revisão e melhoria da Especificação Suplementar
- [x] Foi feita a revisão e melhoria dos Léxico
- [x] Foi feita a revisão e melhoria do NFR Framework

**Comment by pedroeagle** [comment]
criei uma branch para que seja feita a revisão: issue_93_revisao_modelagem

**Comment by heylisten64** [comment]
ontem documentei as duvidas que tivemos e mandei pro monitor, estou no aguardo da resposta

**Comment by juniopereirab** [comment]
Não esqueçam de marcar quando for feita a revisão...

**Comment by lucasgomesgs0** [comment]
Foi criado uma branch para refatorar algumas informações referes a Especificação Suplementar, branch de nome issue_96_refatorar_especificacao_suplementar
